// Generated by body/firmware/tools/embed_assets.py from
// data/body-assets/320x240/manifest.json. Do not edit.
#pragma once
#include <stddef.h>
#include <stdint.h>

namespace gizmo::assets::generated {
constexpr int kPanelWidth = 320;
constexpr int kPanelHeight = 240;
constexpr int kBootSlots = 24;
constexpr int kBootUniqueFrames = 15;
constexpr uint32_t kBootFramePeriodMs = 125;
constexpr uint32_t kBootMinimumMs = 5050;
constexpr uint32_t kBootChimeAtMs = 2875;
constexpr uint32_t kBootDropMs = 1250;
constexpr uint8_t kBootSlotFrame[kBootSlots] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 11, 12, 13, 12, 11, 10, 10, 12, 13, 12, 14};

constexpr uint32_t kChimeSampleRate = 16000;
constexpr size_t kChimeSamples = 10720;

constexpr float kStatusTopFraction = 0.045f;
constexpr int kHearts = 5;
constexpr int kHalfSteps = 10;
constexpr int kHeartLayoutSide = 11;
constexpr int kHeartAssetSide = 14;
constexpr int kClockCellWidth = 11;
constexpr int kClockCellHeight = 21;
constexpr int kClockBaseline = 16;
constexpr int kClockWeight = 500;
constexpr int kClockAtlasWidth = 121;
constexpr int kClockAtlasHeight = 21;
constexpr char kClockCharacters[] = "0123456789:";

// Linker symbols for the embedded blobs (platformio.ini board_build.embed_files).
extern "C" const uint8_t _binary_assets_boot_00_jpg_start[] asm("_binary_assets_boot_00_jpg_start");
extern "C" const uint8_t _binary_assets_boot_00_jpg_end[] asm("_binary_assets_boot_00_jpg_end");
extern "C" const uint8_t _binary_assets_boot_01_jpg_start[] asm("_binary_assets_boot_01_jpg_start");
extern "C" const uint8_t _binary_assets_boot_01_jpg_end[] asm("_binary_assets_boot_01_jpg_end");
extern "C" const uint8_t _binary_assets_boot_02_jpg_start[] asm("_binary_assets_boot_02_jpg_start");
extern "C" const uint8_t _binary_assets_boot_02_jpg_end[] asm("_binary_assets_boot_02_jpg_end");
extern "C" const uint8_t _binary_assets_boot_03_jpg_start[] asm("_binary_assets_boot_03_jpg_start");
extern "C" const uint8_t _binary_assets_boot_03_jpg_end[] asm("_binary_assets_boot_03_jpg_end");
extern "C" const uint8_t _binary_assets_boot_04_jpg_start[] asm("_binary_assets_boot_04_jpg_start");
extern "C" const uint8_t _binary_assets_boot_04_jpg_end[] asm("_binary_assets_boot_04_jpg_end");
extern "C" const uint8_t _binary_assets_boot_05_jpg_start[] asm("_binary_assets_boot_05_jpg_start");
extern "C" const uint8_t _binary_assets_boot_05_jpg_end[] asm("_binary_assets_boot_05_jpg_end");
extern "C" const uint8_t _binary_assets_boot_06_jpg_start[] asm("_binary_assets_boot_06_jpg_start");
extern "C" const uint8_t _binary_assets_boot_06_jpg_end[] asm("_binary_assets_boot_06_jpg_end");
extern "C" const uint8_t _binary_assets_boot_07_jpg_start[] asm("_binary_assets_boot_07_jpg_start");
extern "C" const uint8_t _binary_assets_boot_07_jpg_end[] asm("_binary_assets_boot_07_jpg_end");
extern "C" const uint8_t _binary_assets_boot_08_jpg_start[] asm("_binary_assets_boot_08_jpg_start");
extern "C" const uint8_t _binary_assets_boot_08_jpg_end[] asm("_binary_assets_boot_08_jpg_end");
extern "C" const uint8_t _binary_assets_boot_09_jpg_start[] asm("_binary_assets_boot_09_jpg_start");
extern "C" const uint8_t _binary_assets_boot_09_jpg_end[] asm("_binary_assets_boot_09_jpg_end");
extern "C" const uint8_t _binary_assets_boot_10_jpg_start[] asm("_binary_assets_boot_10_jpg_start");
extern "C" const uint8_t _binary_assets_boot_10_jpg_end[] asm("_binary_assets_boot_10_jpg_end");
extern "C" const uint8_t _binary_assets_boot_11_jpg_start[] asm("_binary_assets_boot_11_jpg_start");
extern "C" const uint8_t _binary_assets_boot_11_jpg_end[] asm("_binary_assets_boot_11_jpg_end");
extern "C" const uint8_t _binary_assets_boot_12_jpg_start[] asm("_binary_assets_boot_12_jpg_start");
extern "C" const uint8_t _binary_assets_boot_12_jpg_end[] asm("_binary_assets_boot_12_jpg_end");
extern "C" const uint8_t _binary_assets_boot_13_jpg_start[] asm("_binary_assets_boot_13_jpg_start");
extern "C" const uint8_t _binary_assets_boot_13_jpg_end[] asm("_binary_assets_boot_13_jpg_end");
extern "C" const uint8_t _binary_assets_boot_14_jpg_start[] asm("_binary_assets_boot_14_jpg_start");
extern "C" const uint8_t _binary_assets_boot_14_jpg_end[] asm("_binary_assets_boot_14_jpg_end");
extern "C" const uint8_t _binary_assets_home_base_jpg_start[] asm("_binary_assets_home_base_jpg_start");
extern "C" const uint8_t _binary_assets_home_base_jpg_end[] asm("_binary_assets_home_base_jpg_end");
extern "C" const uint8_t _binary_assets_heart_empty_rgb565a_start[] asm("_binary_assets_heart_empty_rgb565a_start");
extern "C" const uint8_t _binary_assets_heart_empty_rgb565a_end[] asm("_binary_assets_heart_empty_rgb565a_end");
extern "C" const uint8_t _binary_assets_heart_half_rgb565a_start[] asm("_binary_assets_heart_half_rgb565a_start");
extern "C" const uint8_t _binary_assets_heart_half_rgb565a_end[] asm("_binary_assets_heart_half_rgb565a_end");
extern "C" const uint8_t _binary_assets_heart_full_rgb565a_start[] asm("_binary_assets_heart_full_rgb565a_start");
extern "C" const uint8_t _binary_assets_heart_full_rgb565a_end[] asm("_binary_assets_heart_full_rgb565a_end");
extern "C" const uint8_t _binary_assets_clock_atlas_a8_start[] asm("_binary_assets_clock_atlas_a8_start");
extern "C" const uint8_t _binary_assets_clock_atlas_a8_end[] asm("_binary_assets_clock_atlas_a8_end");
extern "C" const uint8_t _binary_assets_boot_chime_pcm16_start[] asm("_binary_assets_boot_chime_pcm16_start");
extern "C" const uint8_t _binary_assets_boot_chime_pcm16_end[] asm("_binary_assets_boot_chime_pcm16_end");

inline const uint8_t* boot_frame_start(int unique) {
  switch (unique) {
    case 0: return _binary_assets_boot_00_jpg_start;
    case 1: return _binary_assets_boot_01_jpg_start;
    case 2: return _binary_assets_boot_02_jpg_start;
    case 3: return _binary_assets_boot_03_jpg_start;
    case 4: return _binary_assets_boot_04_jpg_start;
    case 5: return _binary_assets_boot_05_jpg_start;
    case 6: return _binary_assets_boot_06_jpg_start;
    case 7: return _binary_assets_boot_07_jpg_start;
    case 8: return _binary_assets_boot_08_jpg_start;
    case 9: return _binary_assets_boot_09_jpg_start;
    case 10: return _binary_assets_boot_10_jpg_start;
    case 11: return _binary_assets_boot_11_jpg_start;
    case 12: return _binary_assets_boot_12_jpg_start;
    case 13: return _binary_assets_boot_13_jpg_start;
    case 14: return _binary_assets_boot_14_jpg_start;
    default: return nullptr;
  }
}
inline const uint8_t* boot_frame_end(int unique) {
  switch (unique) {
    case 0: return _binary_assets_boot_00_jpg_end;
    case 1: return _binary_assets_boot_01_jpg_end;
    case 2: return _binary_assets_boot_02_jpg_end;
    case 3: return _binary_assets_boot_03_jpg_end;
    case 4: return _binary_assets_boot_04_jpg_end;
    case 5: return _binary_assets_boot_05_jpg_end;
    case 6: return _binary_assets_boot_06_jpg_end;
    case 7: return _binary_assets_boot_07_jpg_end;
    case 8: return _binary_assets_boot_08_jpg_end;
    case 9: return _binary_assets_boot_09_jpg_end;
    case 10: return _binary_assets_boot_10_jpg_end;
    case 11: return _binary_assets_boot_11_jpg_end;
    case 12: return _binary_assets_boot_12_jpg_end;
    case 13: return _binary_assets_boot_13_jpg_end;
    case 14: return _binary_assets_boot_14_jpg_end;
    default: return nullptr;
  }
}
}  // namespace gizmo::assets::generated
