from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass
class TransportEvent:
    kind: str
    text: str = ""
    pcm: bytes = b""
    name: str = ""
    arguments: dict[str, Any] = field(default_factory=dict)
    call_id: str = ""
    item_id: str = ""
    raw: dict[str, Any] = field(default_factory=dict)


class Transport(Protocol):
    async def connect(self, instructions: str) -> None: ...
    async def close(self) -> None: ...
    async def send_text(self, text: str) -> None: ...
    async def begin_audio(self) -> None: ...
    async def send_audio(self, pcm: bytes) -> None: ...
    async def commit_audio(self) -> None: ...
    async def interrupt(self, played_ms: int = 0, item_id: str = "") -> None: ...
    async def request_response(self) -> None: ...
    async def submit_tool_output(self, call_id: str, output: str) -> None: ...
    async def send_image(self, data_url: str) -> None: ...
    async def clear_pending_image(self) -> None: ...
    def __aiter__(self) -> Transport: ...
    async def __anext__(self) -> TransportEvent: ...
