#!/usr/bin/env python3
"""Turn an export_bundle.py output into firmware-embedded blobs.

Reads ``data/body-assets/<W>x<H>/manifest.json`` (the same bundle the Mac
reference loader consumes), writes fixed-name binaries into
``body/firmware/assets/`` and a header with every timing/layout constant the
panel code needs. ``platformio.ini`` gets its ``board_build.embed_files`` list
rewritten between the marker comments so the blobs land in flash as
``_binary_assets_<name>_start`` symbols.

    body/firmware/.venv/Scripts/python body/firmware/tools/embed_assets.py \
        --bundle data/body-assets/320x240
"""

from __future__ import annotations

import argparse
import io
import json
import struct
import wave
from pathlib import Path

from PIL import Image

FIRMWARE = Path(__file__).resolve().parents[1]
ASSETS = FIRMWARE / "assets"
HEADER = FIRMWARE / "include" / "gizmo" / "assets_generated.h"
INI = FIRMWARE / "platformio.ini"
DEVICE_SAMPLE_RATE = 16_000
BEGIN = "; BEGIN embed_assets.py"
END = "; END embed_assets.py"


def rgb565a(image: Image.Image) -> bytes:
    """Interleaved little-endian RGB565 + 8-bit alpha, three bytes per pixel."""
    out = bytearray()
    for r, g, b, a in image.convert("RGBA").getdata():
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out += struct.pack("<HB", value, a)
    return bytes(out)


def resample_pcm16(samples: list[int], source_hz: int, target_hz: int) -> list[int]:
    if source_hz == target_hz:
        return samples
    count = int(len(samples) * target_hz / source_hz)
    out = []
    for index in range(count):
        position = index * source_hz / target_hz
        left = int(position)
        right = min(left + 1, len(samples) - 1)
        frac = position - left
        out.append(int(round(samples[left] * (1 - frac) + samples[right] * frac)))
    return out


def load_chime(path: Path) -> tuple[bytes, int]:
    with wave.open(str(path), "rb") as audio:
        assert audio.getnchannels() == 1 and audio.getsampwidth() == 2, "chime must be mono PCM16"
        rate = audio.getframerate()
        raw = audio.readframes(audio.getnframes())
    samples = list(struct.unpack(f"<{len(raw) // 2}h", raw))
    resampled = resample_pcm16(samples, rate, DEVICE_SAMPLE_RATE)
    return struct.pack(f"<{len(resampled)}h", *resampled), len(resampled)


def write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def symbol(name: str) -> str:
    return "_binary_assets_" + "".join(c if c.isalnum() else "_" for c in name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--bundle", type=Path, required=True, help="export_bundle.py output directory")
    args = parser.parse_args()
    bundle = args.bundle.expanduser().resolve()
    manifest = json.loads((bundle / "manifest.json").read_text())
    if manifest.get("schema_version") != 1:
        raise SystemExit("unsupported manifest schema")
    profile = manifest["profile"]
    boot = manifest["boot"]
    home = manifest["home"]

    if ASSETS.exists():
        for stale in ASSETS.iterdir():
            stale.unlink()
    ASSETS.mkdir(parents=True, exist_ok=True)
    embedded: list[str] = []

    # Boot: unique frames in first-appearance order, slot -> unique index map.
    unique: list[str] = []
    slots: list[int] = []
    for relative in boot["sequence"]:
        if relative not in unique:
            unique.append(relative)
        slots.append(unique.index(relative))
    for index, relative in enumerate(unique):
        name = f"boot_{index:02d}.jpg"
        write(ASSETS / name, (bundle / relative).read_bytes())
        embedded.append(name)

    write(ASSETS / "home_base.jpg", (bundle / home["base"]).read_bytes())
    embedded.append("home_base.jpg")

    heart_side = None
    for state in ("empty", "half", "full"):
        with Image.open(bundle / home["battery"]["paths"][state]) as opened:
            heart = opened.convert("RGBA")
            if heart_side is None:
                heart_side = heart.width
            assert heart.size == (heart_side, heart_side), "hearts must be square and equal"
            name = f"heart_{state}.rgb565a"
            write(ASSETS / name, rgb565a(heart))
            embedded.append(name)

    clock = home["clock"]
    with Image.open(bundle / clock["path"]) as opened:
        atlas = opened.convert("L")
        atlas_w, atlas_h = atlas.size
        write(ASSETS / "clock_atlas.a8", atlas.tobytes())
        embedded.append("clock_atlas.a8")

    chime_bytes, chime_samples = load_chime(bundle / boot["chime"]["path"])
    write(ASSETS / "boot_chime.pcm16", chime_bytes)
    embedded.append("boot_chime.pcm16")

    entrance = boot.get("entrance") or {}
    lines = [
        "// Generated by body/firmware/tools/embed_assets.py from",
        f"// {bundle.relative_to(FIRMWARE.parents[1]).as_posix()}/manifest.json. Do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace gizmo::assets::generated {",
        f"constexpr int kPanelWidth = {profile['width']};",
        f"constexpr int kPanelHeight = {profile['height']};",
        f"constexpr int kBootSlots = {len(slots)};",
        f"constexpr int kBootUniqueFrames = {len(unique)};",
        f"constexpr uint32_t kBootFramePeriodMs = {boot['frame_period_ms']};",
        f"constexpr uint32_t kBootMinimumMs = {boot['minimum_duration_ms']};",
        f"constexpr uint32_t kBootChimeAtMs = {boot['chime_at_ms']};",
        f"constexpr uint32_t kBootDropMs = {int(entrance.get('duration_ms', 0))};",
        f"constexpr uint8_t kBootSlotFrame[kBootSlots] = {{{', '.join(str(s) for s in slots)}}};",
        "",
        f"constexpr uint32_t kChimeSampleRate = {DEVICE_SAMPLE_RATE};",
        f"constexpr size_t kChimeSamples = {chime_samples};",
        "",
        f"constexpr float kStatusTopFraction = {home['status_top_fraction']}f;",
        f"constexpr int kHearts = {home['battery']['hearts']};",
        f"constexpr int kHalfSteps = {home['battery']['half_steps']};",
        f"constexpr int kHeartLayoutSide = {home['battery']['layout_side']};",
        f"constexpr int kHeartAssetSide = {heart_side};",
        f"constexpr int kClockCellWidth = {clock['cell_width']};",
        f"constexpr int kClockCellHeight = {clock['cell_height']};",
        f"constexpr int kClockBaseline = {clock['baseline']};",
        f"constexpr int kClockWeight = {int(clock.get('weight', 500))};",
        f"constexpr int kClockAtlasWidth = {atlas_w};",
        f"constexpr int kClockAtlasHeight = {atlas_h};",
        f"constexpr char kClockCharacters[] = \"{clock['characters']}\";",
        "",
        "// Linker symbols for the embedded blobs (platformio.ini board_build.embed_files).",
    ]
    for name in embedded:
        sym = symbol(name)
        lines.append(f'extern "C" const uint8_t {sym}_start[] asm("{sym}_start");')
        lines.append(f'extern "C" const uint8_t {sym}_end[] asm("{sym}_end");')
    lines.append("")
    lines.append("inline const uint8_t* boot_frame_start(int unique) {")
    lines.append("  switch (unique) {")
    for index in range(len(unique)):
        lines.append(f"    case {index}: return {symbol(f'boot_{index:02d}.jpg')}_start;")
    lines.append("    default: return nullptr;")
    lines.append("  }")
    lines.append("}")
    lines.append("inline const uint8_t* boot_frame_end(int unique) {")
    lines.append("  switch (unique) {")
    for index in range(len(unique)):
        lines.append(f"    case {index}: return {symbol(f'boot_{index:02d}.jpg')}_end;")
    lines.append("    default: return nullptr;")
    lines.append("  }")
    lines.append("}")
    lines.append("}  // namespace gizmo::assets::generated")
    lines.append("")
    HEADER.write_text("\n".join(lines))

    ini = INI.read_text()
    begin = ini.index(BEGIN)
    end = ini.index(END) + len(END)
    block = "\n".join([BEGIN, "board_build.embed_files ="] + [f"    assets/{name}" for name in embedded] + [END])
    INI.write_text(ini[:begin] + block + ini[end:])

    total = sum((ASSETS / name).stat().st_size for name in embedded)
    print(json.dumps({
        "status": "embedded",
        "files": len(embedded),
        "boot_unique_frames": len(unique),
        "boot_slots": len(slots),
        "chime_samples_16k": chime_samples,
        "heart_side": heart_side,
        "total_bytes": total,
        "header": HEADER.relative_to(FIRMWARE).as_posix(),
    }, indent=2))


if __name__ == "__main__":
    main()
