#!/usr/bin/env python3
"""Embed the reviewed public CA roots; no network access or private keys."""
from pathlib import Path

firmware = Path(__file__).resolve().parents[1]
certificates = ''.join(path.read_text() for path in sorted((firmware / 'certs').glob('*.pem')))
if not certificates or 'PRIVATE KEY' in certificates:
    raise SystemExit('expected public certificates in certs/*.pem')
(firmware / 'include/gizmo/trust_roots.h').write_text(
    '#pragma once\n'
    '// Generated by tools/embed_trust_roots.py. See certs/README.md.\n'
    'namespace gizmo {\n'
    'inline constexpr char kFriendRootCAs[] = R"PEM(' + certificates + ')PEM";\n}\n'
)
